[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "virtualos-rs"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
nix = { workspace = true, features = ["mount", "sched", "hostname"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

# ------------ local deps ------------
ebpf = { path = "../ebpf" }
engine = { path = "../engine" }
daemon = { path = "../daemon" }
logging = { path = "../logging" }
monitoring = { path = "../monitoring" }
network = { path = "../network" }
storage = { path = "../storage" }
virtualization = { path = "../virtualization" }
