[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tonic = "0.14.6"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-stream = "0.1.18"

# --------- local deps -----------
engine = { path = "../engine" }
cgroups = { path = "../cgroups" }
logging = { path = "../logging" }
network = { path = "../network" }
proto = { path = "../proto" }
storage = { path = "../storage" }
